name: Plugin Verification Request
description: Request verification for your plugin
title: homebridge-
labels:
  - pending-review
body:
  - type: markdown
    attributes:
      value: "## Basic Details"
  - type: markdown
    attributes:
      value: >
        Please double check the [requirements
        list](https://github.com/homebridge/verified#requirements) before
        submitting a request.
  - type: input
    attributes:
      label: Link To GitHub Repo
      placeholder: https://github.com/homebridge/homebridge-xyz
    validations:
      required: true
  - type: input
    attributes:
      label: Link To NPM Package
      placeholder: https://www.npmjs.com/package/homebridge-xyz
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin Icon (Optional)
      description: Please attach the icon you would like to use. This must be a square
        image, around 100px by 100px, and in PNG format. Please ensure that any
        icon will not violate any trademark or licensing agreements.
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Verification Requirements"
  - type: markdown
    attributes:
      value: "### General"
  - type: markdown
    attributes:
      value: "Please answer/confirm the following conditions:"
  - type: dropdown
    attributes:
      label: The plugin is of type dynamic platform.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The plugin does not offer the same nor less functionality than that of
        any existing verified plugin.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Repo"
  - type: dropdown
    attributes:
      label: The plugin is published to NPM and the source code is available on a
        GitHub repository, with issues enabled.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: A GitHub release is created for every new version of your plugin, with
        release notes.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Environment"
  - type: dropdown
    attributes:
      label: The plugin runs on all supported LTS versions of Node.js, at the time of
        writing this is Node v18 and v20.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The plugin successfully installs and does not start unless it is
        configured.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The plugin does not execute post-install scripts that modify the users
        system in any way.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The plugin does not require the user to run Homebridge in a TTY or with
        non-standard startup parameters, even for initial configuration.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Codebase"
  - type: dropdown
    attributes:
      label: The plugin implements the Homebridge Plugin Settings GUI.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The plugin does not contain any analytics or calls that enable you to
        track the user.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: If the plugin needs to write files to disk (cache, keys, etc.), it stores
        them inside the Homebridge storage directory.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: The plugin does not throw unhandled exceptions, the plugin must catch and
        log its own errors.
      options:
        - Choose an option...
        - 🟢 Yes
        - 🟠 No (please explain in the more information box at the end)
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## More Information"
  - type: textarea
    attributes:
      label: More Information
      description: Please provide any additional information that you think is relevant
        to the review process. This is a place to explain any "No" answers from
        above.
