name: Plugin Pre-Checks (Schedule)
on:
  schedule:
    - cron: "0 0,6,12,18 * * *"

jobs:
  check-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --prefix precheck
      - name: Randomly Select Plugin
        id: get-verified-plugin
        run: |
          echo "plugin=$(jq -r '.[]' verified-plugins.json | sed '/^$/d' | shuf -n 1)" >> $GITHUB_ENV
        shell: bash
      - name: Check Plugin
        uses: ./precheck
        with:
          plugin: ${{ env.plugin }}
